sudo: false
language: node_js
node_js:
  - '10'
cache: npm
install:
  - npm i
before_script:
  - npm i nyc mocha -g
script:
  - npm run cov
after_success:
  - bash <(curl -s https://codecov.io/bash) -t a220b5d5-c7be-407f-b94a-83d0f85234c0
